# Generated by Django 4.1.2 on 2022-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='car.feature'),
        ),
    ]
