# Generated by Django 4.1.2 on 2022-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(help_text='holds the name of the car', max_length=200, unique=True),
        ),
    ]
