# Generated by Django 4.1.2 on 2022-10-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclemodels',
            unique_together={('brand', 'name')},
        ),
    ]
